//! Remote-MCP connector catalog — static data table of known MCP servers.
//! Extracted from `mcp.rs`; pure data, no behavior.

/// MCP catalog entry
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CatalogEntry {
    pub slug: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub docs_url: Option<String>,
    pub requires_token: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo_svg: Option<String>,
}

pub fn get_catalog() -> Vec<CatalogEntry> {
    vec![
        // Productivity (10)
        CatalogEntry {
            slug: "atlassian".to_string(),
            name: "Atlassian".to_string(),
            description: "Connect Jira, Confluence, and other Atlassian tools".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.atlassian.com/v1/mcp".to_string(),
            docs_url: Some("https://developer.atlassian.com/cloud/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "notion".to_string(),
            name: "Notion".to_string(),
            description: "Access and manage your Notion workspace".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.notion.com/v1".to_string(),
            docs_url: Some("https://developers.notion.com/docs/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "linear".to_string(),
            name: "Linear".to_string(),
            description: "Manage Linear issues and projects".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.linear.app/sse".to_string(),
            docs_url: Some("https://linear.app/docs/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "zapier".to_string(),
            name: "Zapier".to_string(),
            description: "Automate workflows across thousands of apps".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.zapier.com/v1".to_string(),
            docs_url: Some("https://zapier.com/docs/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "asana".to_string(),
            name: "Asana".to_string(),
            description: "Manage tasks and projects in Asana".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.asana.com/v1".to_string(),
            docs_url: Some("https://developers.asana.com/docs/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "airtable".to_string(),
            name: "Airtable".to_string(),
            description: "Access and modify Airtable bases and records".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.airtable.com/v1".to_string(),
            docs_url: Some("https://airtable.com/developers/web/api/introduction".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "monday".to_string(),
            name: "Monday.com".to_string(),
            description: "Manage boards and items in Monday.com".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.monday.com/v1".to_string(),
            docs_url: Some("https://developer.monday.com/apps/docs/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "clickup".to_string(),
            name: "ClickUp".to_string(),
            description: "Manage tasks and docs in ClickUp".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.clickup.com/v1".to_string(),
            docs_url: Some("https://clickup.com/api/developer-portal/mcp".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "trello".to_string(),
            name: "Trello".to_string(),
            description: "Access boards, lists and cards in Trello".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.trello.com/v1".to_string(),
            docs_url: Some("https://developer.atlassian.com/cloud/trello/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "coda".to_string(),
            name: "Coda".to_string(),
            description: "Read and write Coda docs and tables".to_string(),
            category: "Productivity".to_string(),
            url: "https://mcp.coda.io/v1".to_string(),
            docs_url: Some("https://coda.io/developers/apis/v1".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Google (7)
        CatalogEntry {
            slug: "google-drive".to_string(),
            name: "Google Drive".to_string(),
            description: "Access and manage files in Google Drive".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/drive/v1".to_string(),
            docs_url: Some("https://developers.google.com/drive/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "gmail".to_string(),
            name: "Gmail".to_string(),
            description: "Read and send emails via Gmail".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/gmail/v1".to_string(),
            docs_url: Some("https://developers.google.com/gmail/api/guides".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "google-calendar".to_string(),
            name: "Google Calendar".to_string(),
            description: "Manage events in Google Calendar".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/calendar/v1".to_string(),
            docs_url: Some("https://developers.google.com/calendar/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "google-docs".to_string(),
            name: "Google Docs".to_string(),
            description: "Create and edit Google Docs".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/docs/v1".to_string(),
            docs_url: Some("https://developers.google.com/docs/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "google-sheets".to_string(),
            name: "Google Sheets".to_string(),
            description: "Read and write Google Sheets spreadsheets".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/sheets/v1".to_string(),
            docs_url: Some("https://developers.google.com/sheets/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "google-slides".to_string(),
            name: "Google Slides".to_string(),
            description: "Create and manage Google Slides presentations".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/slides/v1".to_string(),
            docs_url: Some("https://developers.google.com/slides/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "youtube".to_string(),
            name: "YouTube".to_string(),
            description: "Access YouTube data and manage content".to_string(),
            category: "Google".to_string(),
            url: "https://mcp.googleapis.com/youtube/v1".to_string(),
            docs_url: Some("https://developers.google.com/youtube/v3".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Development (8)
        CatalogEntry {
            slug: "github".to_string(),
            name: "GitHub".to_string(),
            description: "Manage repositories, issues, and pull requests".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.github.com/v1".to_string(),
            docs_url: Some("https://docs.github.com/en/rest".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "gitlab".to_string(),
            name: "GitLab".to_string(),
            description: "Access GitLab projects and CI/CD pipelines".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.gitlab.com/v1".to_string(),
            docs_url: Some("https://docs.gitlab.com/ee/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "bitbucket".to_string(),
            name: "Bitbucket".to_string(),
            description: "Manage Bitbucket repositories and pipelines".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.bitbucket.com/v1".to_string(),
            docs_url: Some("https://developer.atlassian.com/cloud/bitbucket/rest".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "vercel".to_string(),
            name: "Vercel".to_string(),
            description: "Deploy and manage projects on Vercel".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.vercel.com/v1".to_string(),
            docs_url: Some("https://vercel.com/docs/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "heroku".to_string(),
            name: "Heroku".to_string(),
            description: "Deploy and manage apps on Heroku".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.heroku.com/v1".to_string(),
            docs_url: Some("https://devcenter.heroku.com/articles/platform-api-reference".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "aws".to_string(),
            name: "Amazon AWS".to_string(),
            description: "Access and manage AWS resources".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.aws.amazon.com/v1".to_string(),
            docs_url: Some("https://docs.aws.amazon.com/sdk".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "azure".to_string(),
            name: "Microsoft Azure".to_string(),
            description: "Manage Azure resources and services".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.azure.com/v1".to_string(),
            docs_url: Some("https://learn.microsoft.com/en-us/azure".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "gcp".to_string(),
            name: "Google Cloud Platform".to_string(),
            description: "Access GCP resources and services".to_string(),
            category: "Development".to_string(),
            url: "https://mcp.googleapis.com/cloud/v1".to_string(),
            docs_url: Some("https://cloud.google.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Communication (5)
        CatalogEntry {
            slug: "slack".to_string(),
            name: "Slack".to_string(),
            description: "Send messages and manage Slack workspaces".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.slack.com/v1".to_string(),
            docs_url: Some("https://api.slack.com".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "discord".to_string(),
            name: "Discord".to_string(),
            description: "Manage Discord servers and send messages".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.discord.com/v1".to_string(),
            docs_url: Some("https://discord.com/developers/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "telegram".to_string(),
            name: "Telegram".to_string(),
            description: "Send messages via Telegram bot".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.telegram.org/v1".to_string(),
            docs_url: Some("https://core.telegram.org/bots/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "twilio".to_string(),
            name: "Twilio".to_string(),
            description: "Send SMS and voice messages".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.twilio.com/v1".to_string(),
            docs_url: Some("https://www.twilio.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "sendgrid".to_string(),
            name: "SendGrid".to_string(),
            description: "Send emails with SendGrid".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.sendgrid.com/v1".to_string(),
            docs_url: Some("https://docs.sendgrid.com".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "zoom".to_string(),
            name: "Zoom".to_string(),
            description: "Schedule meetings and manage Zoom integrations".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.zoom.us/v1".to_string(),
            docs_url: Some("https://developers.zoom.us/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "intercom".to_string(),
            name: "Intercom".to_string(),
            description: "Manage customer conversations and support".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.intercom.com/v1".to_string(),
            docs_url: Some("https://developers.intercom.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "zendesk".to_string(),
            name: "Zendesk".to_string(),
            description: "Manage support tickets and customer service".to_string(),
            category: "Communication".to_string(),
            url: "https://mcp.zendesk.com/v1".to_string(),
            docs_url: Some("https://developer.zendesk.com/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Data & Analytics (5)
        CatalogEntry {
            slug: "datadog".to_string(),
            name: "Datadog".to_string(),
            description: "Monitor and analyze metrics with Datadog".to_string(),
            category: "Data & Analytics".to_string(),
            url: "https://mcp.datadoghq.com/v1".to_string(),
            docs_url: Some("https://docs.datadoghq.com/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "elastic".to_string(),
            name: "Elastic".to_string(),
            description: "Search and analyze data with Elastic".to_string(),
            category: "Data & Analytics".to_string(),
            url: "https://mcp.elastic.co/v1".to_string(),
            docs_url: Some("https://www.elastic.co/guide/en/elasticsearch/reference".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "mixpanel".to_string(),
            name: "Mixpanel".to_string(),
            description: "Track and analyze user analytics".to_string(),
            category: "Data & Analytics".to_string(),
            url: "https://mcp.mixpanel.com/v1".to_string(),
            docs_url: Some("https://developer.mixpanel.com".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "segment".to_string(),
            name: "Segment".to_string(),
            description: "Collect and manage customer data".to_string(),
            category: "Data & Analytics".to_string(),
            url: "https://mcp.segment.com/v1".to_string(),
            docs_url: Some("https://segment.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "tableau".to_string(),
            name: "Tableau".to_string(),
            description: "Create and share data visualizations".to_string(),
            category: "Data & Analytics".to_string(),
            url: "https://mcp.tableau.com/v1".to_string(),
            docs_url: Some("https://help.tableau.com/current/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Finance (3)
        CatalogEntry {
            slug: "stripe".to_string(),
            name: "Stripe".to_string(),
            description: "Process payments and manage subscriptions".to_string(),
            category: "Finance".to_string(),
            url: "https://mcp.stripe.com/v1".to_string(),
            docs_url: Some("https://stripe.com/docs/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "square".to_string(),
            name: "Square".to_string(),
            description: "Manage payments and invoices".to_string(),
            category: "Finance".to_string(),
            url: "https://mcp.squareup.com/v1".to_string(),
            docs_url: Some("https://developer.squareup.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "quickbooks".to_string(),
            name: "QuickBooks".to_string(),
            description: "Manage accounting and invoices".to_string(),
            category: "Finance".to_string(),
            url: "https://mcp.quickbooks.intuit.com/v1".to_string(),
            docs_url: Some("https://developer.intuit.com/app/developer/qbo/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Design (2)
        CatalogEntry {
            slug: "figma".to_string(),
            name: "Figma".to_string(),
            description: "Access and manage Figma designs and files".to_string(),
            category: "Design".to_string(),
            url: "https://mcp.figma.com/v1".to_string(),
            docs_url: Some("https://www.figma.com/developers/api".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "adobe-creative-cloud".to_string(),
            name: "Adobe Creative Cloud".to_string(),
            description: "Access Adobe Creative Cloud applications".to_string(),
            category: "Design".to_string(),
            url: "https://mcp.adobe.com/v1".to_string(),
            docs_url: Some("https://developer.adobe.com/console".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // CRM (2)
        CatalogEntry {
            slug: "salesforce".to_string(),
            name: "Salesforce".to_string(),
            description: "Manage Salesforce CRM data and contacts".to_string(),
            category: "CRM".to_string(),
            url: "https://mcp.salesforce.com/v1".to_string(),
            docs_url: Some("https://developer.salesforce.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "hubspot".to_string(),
            name: "HubSpot".to_string(),
            description: "Manage HubSpot CRM, marketing, and sales".to_string(),
            category: "CRM".to_string(),
            url: "https://mcp.hubapi.com/v1".to_string(),
            docs_url: Some("https://developers.hubspot.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Backend & Databases (3)
        CatalogEntry {
            slug: "supabase".to_string(),
            name: "Supabase".to_string(),
            description: "Access Supabase PostgreSQL databases and storage".to_string(),
            category: "Backend".to_string(),
            url: "https://mcp.supabase.com/v1".to_string(),
            docs_url: Some("https://supabase.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "firebase".to_string(),
            name: "Firebase".to_string(),
            description: "Access Firebase database and services".to_string(),
            category: "Backend".to_string(),
            url: "https://mcp.firebase.com/v1".to_string(),
            docs_url: Some("https://firebase.google.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        CatalogEntry {
            slug: "mongodb".to_string(),
            name: "MongoDB".to_string(),
            description: "Query and manage MongoDB databases".to_string(),
            category: "Backend".to_string(),
            url: "https://mcp.mongodb.com/v1".to_string(),
            docs_url: Some("https://www.mongodb.com/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Marketing (1)
        CatalogEntry {
            slug: "mailchimp".to_string(),
            name: "Mailchimp".to_string(),
            description: "Manage email campaigns and marketing lists".to_string(),
            category: "Marketing".to_string(),
            url: "https://mcp.mailchimp.com/v1".to_string(),
            docs_url: Some("https://mailchimp.com/developer".to_string()),
            requires_token: true,
            logo_svg: None,
        },
        // Streaming (1)
        CatalogEntry {
            slug: "twitch".to_string(),
            name: "Twitch".to_string(),
            description: "Access Twitch channels and stream data".to_string(),
            category: "Streaming".to_string(),
            url: "https://mcp.twitch.tv/v1".to_string(),
            docs_url: Some("https://dev.twitch.tv/docs".to_string()),
            requires_token: true,
            logo_svg: None,
        },
    ]
}
